import type { Metadata } from 'next'
import { Inter as FontSans } from 'next/font/google'
import '@/assets/global.css'
import TanstackProvider from '@/components/providers/TanstackProvider'
import Footer from '@/containers/Footer'
import { cn } from '@/lib/utils'

export const fontSans = FontSans({
  subsets: ['latin'],
  variable: '--font-display',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang='en' data-theme='bumblebee'>
      <body className={cn('bg-background font-display min-h-screen antialiased', fontSans.variable)}>
        <TanstackProvider>
          {children}
          <Footer />
        </TanstackProvider>
      </body>
    </html>
  )
}
