import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import '@/assets/tailwind.css'
import Footer from '@/containers/Footer'
import TanstackProvider from '@/contexts/TanstackProvider'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang='en' data-theme='light'>
      <body className={inter.className}>
        <TanstackProvider>
          {children}
          <Footer />
        </TanstackProvider>
      </body>
    </html>
  )
}
